### ISSUE TITLE
Custom Type Encoders and 'composed types'

### ISSUE THREAD

**Issue by Fairlight8** [kodemore/chili#14]
Hello again!

I am again finding myself in a dead end, and I don't know if this behavior is intended or not.

This test code comes from tests/usecases/custom_type_test.py:

```
from chili import encodable, Encoder, TypeEncoder

class ISBN(str):
    def __init__(self, value: str):
        self.value = value

@encodable
class Book:
    name: str
    isbn: ISBN

    def __init__(self, name: str, isbn: ISBN):
        self.name = name
        self.isbn = isbn


class ISBNEncoder(TypeEncoder):
    def encode(self, isbn: ISBN) -> str:
        return isbn.value

encoder = Encoder[Book]({ISBN: ISBNEncoder()})
book = Book("The Hobbit", ISBN("1234567890"))


result = encoder.encode(book)

print(result)
```

Thta code works flawlessly. However, if you change `ISBN` for `list[ISBN]` or any other thing, like a dictionary of ISBNS, it stops working:

```
from chili import encodable, Encoder, TypeEncoder

class ISBN(str):
    def __init__(self, value: str):
        self.value = value

@encodable
class Book:
    name: str
    isbn: list[ISBN]

    def __init__(self, name: str, isbn: ISBN):
        self.name = name
        self.isbn = isbn


class ISBNEncoder(TypeEncoder):
    def encode(self, isbn: ISBN) -> str:
        return isbn.value

encoder = Encoder[Book]({ISBN: ISBNEncoder()})
book = Book("The Hobbit", [ISBN("1234567890"), ISBN("1234567890456456")])

result = encoder.encode(book)

print(result)
```

I assume that the type encoder looks for List[ISBN] and does not find it. But if you have a ISBNEncoder, it should already work?

**Comment by dkraczkowski** [comment]
@Fairlight8 Sounds like a potential bug, will have a look at it after my work today and update you.

**Comment by Fairlight8** [comment]
I think I have the reason and the solution. I inspected your code and I see that you use recursion, when building the type encoders. There are two arguments, a_type, and extra_encoders. The thing is that, you don't pass the extra encoders (or decoders) when doing the recursion. In fact, I think I solved that with a small change. Do you want me to submit a PR?

**Comment by dkraczkowski** [comment]
@Fairlight8 sure ;)

**Comment by dkraczkowski** [comment]
Actually I have fixed it and also added support for NewType and TypeVar ;) please update to 2.1.0 :)

**Comment by Fairlight8** [comment]
Oh, that's also great!! I am upgrading right now, to test the changes, and keep implementing it. Thanks a lot for the library AND the updates!! :)

**Comment by Fairlight8** [comment]
Hey again, @dkraczkowski ! I'm afraid that the problematic code is still not working. When changing ISBN for List[ISBN], it still gives an exception. Same issue as before. I created a PR : #15. I think that solves the issue when nesting subtypes.
